name: Build Windows Qt OpenCASCADE Project

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  build-windows:
    runs-on: windows-latest
    env:
      QT_VERSION: '5.14.0'
      QT_ARCH: 'win64_msvc2017_64'
      OCC_VERSION: '7.7.0'
      OCC_VERSION_TAG: 'V7_7_0' # 用于源码下载
      OCC_ZIP_sha256: '82afb7bd5fd7097189ee4e98bf3bc02b4030cae7a82967db68d5f2b556801779'
      VS_VERSION: 'Visual Studio 16 2019'
      QT_ROOT: 'C:\Qt'
      OCC_ROOT: 'C:\opencascade'
      VCPKG_ROOT: 'C:\vcpkg'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Cache Qt
      id: cache-qt
      uses: actions/cache@v4
      with:
        path: ${{ env.QT_ROOT }}
        key: ${{ runner.os }}-Qt-${{ env.QT_VERSION }}-${{ env.QT_ARCH }}
        
    - name: Install Qt 5.14.0
      uses: jurplel/install-qt-action@v3
      with:
        version: ${{ env.QT_VERSION }}
        arch: ${{ env.QT_ARCH }}
        cached: ${{ steps.cache-qt.outputs.cache-hit }}
        modules: 'qtcharts qtdatavis3d qtnetworkauth'
        
    - name: Cache OpenCASCADE archive
      id: cache-opencascade
      uses: actions/cache@v4
      with:
        path: OpenCASCADE-${{env.OCC_VERSION}}-vc14-64.zip
        key: ${{ runner.os }}-OpenCASCADE-${{ env.OCC_VERSION }}-precompiled-msvc

    - name: Download OpenCascade
      if: steps.cache-occ.outputs.cache-hit != 'true'
      uses: carlosperate/download-file-action@v2
      with:
          file-url: 'https://www.fougue.pro/share/bin/OpenCASCADE-${{env.OCC_VERSION}}-vc14-64.zip'
          sha256: ${{matrix.OCC_ZIP_sha256}}

    - name: Get count of CPU cores
      uses: SimenB/github-actions-cpu-cores@v1
      id: cpu-cores

    - name: Configure Compiler
      uses: ilammy/msvc-dev-cmd@v1

    - name: Build
      shell: cmd
      run: |
          mkdir ${{github.workspace}}\build
          cd ${{github.workspace}}\build
          cmake --version
          cmake .. ^
                -DOpenCASCADE_DIR=../OpenCASCADE-${{matrix.occ_version}}-vc14-64/opencascade-${{matrix.occ_version}} 
          cmake --build . ^
                --config Release ^
                --parallel ${{steps.cpu-cores.outputs.count}}

    - name: Upload logs on failure
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: build-logs
        path: |
          build/**/*.log
          CMakeFiles/**/*.log
        retention-days: 7
